#!/bin/bash
echo "Изменяем hostname VM"
hostnamectl set-hostname slave #название устройства
systemctl restart systemd-hostnamed #перезапускаем службу
echo "Отключаем стандартный Firewall"
systemctl disable firewalld #удаляем из автозагрузки firewalld
systemctl stop firewalld #выключаем firewalld
echo "Устанавливаем другой Firewall"
dnf install -q -y iptables-services #устанавливаем iptables 
cp ./iptables /etc/sysconfig/iptables #копируем настройки фаерволла
systemctl restart iptables #рестартуем фаерволл
systemctl enable iptables #включаем в автозагрузку
echo "Выключение Selinux"
sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config  #изменяем положение селинукс
setenforce 0 #выключаем селинукс
#установка докера
echo "Устанавливаем Docker"
sudo yum install -q -y yum-utils 
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -q -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin #добавление репозитория
systemctl start docker #стартуем докер
systemctl enable docker #включаем докер в автозагрузку
echo "Ставим slave MySQL"
docker pull -q mysql/mysql-server:8.0 #скачиваем образ MySQL
docker run -d --name=slave_mysql --hostname=slave -v $PWD/d1:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=mypass mysql/mysql-server:8.0 --server-id=2  #запускаем контейнер со слейвом
echo "Устанавливаем Java"
dnf install -q -y java #устнавливаем java-openjdk
echo "Устанавливаем Elasticsearch"
rpm --install elasticsearch-8.9.2-x86_64.rpm  #устанавливаем еластик
cp ./jvm.options /etc/elasticsearch/jvm.options.d
systemctl daemon-reload #обновляем конфигурацию
systemctl start elasticsearch #стартуем эластик
systemctl enable --now elasticsearch.service #добавляем еластик в автозагрузку
cp ./elasticsearch.yml /etc/elasticsearch/ #копируем наши настройки эластика 
systemctl daemon-reload #обновляем конфигурацию
systemctl restart elasticsearch #рестартуем еластик 
curl http://localhost:9200 #курлим эластик
echo "Установливаем Kibana"
rpm --install kibana-8.9.2-x86_64.rpm #устанавливаем кибану
systemctl daemon-reload #обновляем конфигурацию
systemctl enable --now kibana.service #добавляем кибану в автозагрузку
cp ./kibana.yml /etc/kibana/kibana.yml #копируем настройки кибаны в директорию
systemctl restart kibana #рестартуем кибану
echo "Установливаем Logstash"
rpm --install logstash-8.9.2-x86_64.rpm #устанавливаем логсташ
systemctl enable --now logstash.service #добавляем логсташ в автозагрузку
cp ./logstash.yml /etc/logstash/logstash.yml #копируем настройки логсташ в директорию
cp ./logstash-nginx-es.conf /etc/logstash/conf.d/logstash-nginx-es.conf #копируем настройки логсташ в директорию
systemctl restart logstash.service #рестартуем логсташ
echo "Установливаем Filebeat"
rpm --install filebeat-8.9.2-x86_64.rpm #устанавливаем битс
cp ./filebeat.yml /etc/filebeat/filebeat.yml #копируем настройки битса в директорию
systemctl restart filebeat #рестартуем битс
